apiVersion: apps/v1
kind: Deployment
metadata:
  name: myinsuranceapp-deployment-az
  labels:
    app: myinsuranceapp-az
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myinsuranceapp-az
  template:
    metadata:
      labels:
        app: myinsuranceapp-az
    spec:
      imagePullSecrets:
      - name: acr-secret 
      containers:
      - name: myinsuranceapp-deployment-az
        image:  risunmyinsuranceapp.azurecr.io/myinsuranceapp:v3
        ports:
        - name: http
          containerPort: 5000